#requirements for unit classifier
name: unit_classifier
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - ipython=8.11.0
  - python=3.11.0
  - numpy=1.24.2
  - scipy=1.10.1
  - scikit-learn=1.2.2
  - pandas=1.5.3
  - matplotlib-base=3.7.1
  - openpyxl=3.1.2
